Description: >
  Cloudfront distribution for UdaPeople.

Parameters:
  WorkflowID:
    Description: Unique identifier.
    Type: String
  S3WebsiteURL:
    Description: Unique identifier.
    Type: String
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: "Custom origin CloudFront distribution"
        Enabled: true
        Origins:
          - Id: custom-origin
            DomainName: !Sub ${S3WebsiteURL}
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: custom-origin
          ViewerProtocolPolicy: allow-all
          ForwardedValues:
            QueryString: false
          MinTTL: 0
        # DefaultRootObject: index.html
Outputs:
  WorkflowID:
    Value: !Sub ${WorkflowID}
    Description: URL for website hosted on S3
    Export:
      Name: WorkflowID
